name: Latest blog posts workflow 
on: 
  schedule: [{ cron: "0 */12 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main", "blog-workflow"] }
jobs: 
    update-readme-with-blog: 
        name: Update README with latest blog posts from dev
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "6"
                feed_list: "https://dev.to/feed/vignesh-j" 
                commit_message: "docs: update latest blog posts"
                committer_username: "blog-buddy"
